apps/administrator/exams/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Alternative
    url(r'^prova/(?P<exam>[0-9]+)/question/(?P<question>[0-9]+)/alternative/add/$', views.AlternativeCreate.as_view(), name = 'alternative_add'),
    url(r'^prova/(?P<exam>[0-9]+)/question/(?P<question>[0-9]+)/alternative/(?P<pk>[0-9]+)/update/$', views.AlternativeUpdate.as_view(), name = 'alternative_update'),
    url(r'^prova/(?P<exam>[0-9]+)/question/(?P<question>[0-9]+)/alternative/(?P<pk>[0-9]+)/delete/$', views.AlternativeDelete.as_view(), name = 'alternative_delete'),
    # Questions
    url(r'^prova/(?P<exam>[0-9]+)/questao/add/$', views.QuestionCreate.as_view(), name = 'question_add'),
    url(r'^prova/(?P<exam>[0-9]+)/questao/(?P<pk>[0-9]+)/update/$', views.QuestionUpdate.as_view(), name = 'question_update'),
    url(r'^prova/(?P<exam>[0-9]+)/questao/(?P<pk>[0-9]+)/delete/$', views.QuestionDelete.as_view(), name = 'question_delete'),
    url(r'^prova/(?P<exam>[0-9]+)/questao/(?P<pk>[0-9]+)/$', views.QuestionDetail.as_view(), name = 'question_detail'),
    # Exams
    url(r'^prova/(?P<exam>[0-9]+)/relatorio/data/$', views.ExamReportData.as_view(), name = 'exam_report_data'),
    url(r'^prova/(?P<exam>[0-9]+)/relatorio/$', views.ExamReport.as_view(), name = 'exam_report'),
    url(r'^prova/(?P<exam>[0-9]+)/delete/$', views.ExamDelete.as_view(), name = 'exam_delete'),
    url(r'^prova/(?P<exam>[0-9]+)/close/$', views.ExamCloseView.as_view(), name = 'exam_close'),
    url(r'^prova/(?P<exam>[0-9]+)/activate/$', views.ExamActivateView.as_view(), name = 'exam_activate'),
    url(r'^prova/add/$', views.ExamCreate.as_view(), name = 'exam_add'),
    url(r'^prova/(?P<exam>[0-9]+)/update/$', views.ExamUpdate.as_view(), name = 'exam_update'),
    url(r'^prova/(?P<exam>[0-9]+)/$', views.ExamDetail.as_view(), name = 'exam_detail'),
    url(r'^(?P<page>[0-9]+)/$', views.ExamList.as_view(), name = 'exam_list_pag'),
    url(r'^$', views.ExamList.as_view(), name = 'exam_list'),
]

settings/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap
admin.autodiscover()

urlpatterns = [
    url(r'', include("apps.administrator.main.urls")),
    url(r'^api/', include("apps.api.urls")),
    # url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': { 'static': StaticViewSitemap }}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt/$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^admin/', include(admin.site.urls)),
]

apps/administrator/exams/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

class Exam(models.Model):
    user = models.ForeignKey(User, verbose_name="Usuário")
    name = models.CharField(max_length=100, verbose_name="Nome")
    date = models.DateField(verbose_name="Data")
    active = models.BooleanField(default=False, verbose_name="Ativo?")
    closed = models.BooleanField(default=False, verbose_name="Fechada?")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "Prova"
        verbose_name_plural = "Provas"

    def get_absolute_url(self):
        return reverse('exam_detail', kwargs={'exam': self.pk})

class Question(models.Model):
    exam = models.ForeignKey(Exam, verbose_name="Prova")
    text = models.CharField(max_length=100, verbose_name="Texto")
    right_alternative = models.OneToOneField("Alternative", related_name="question_right_alternative", blank=True, null=True, default=None)

    def __unicode__(self):
        return self.text

    class Meta:
        verbose_name = "Questão"
        verbose_name_plural = "Questões"

    def get_absolute_url(self):
        return reverse('question_detail', kwargs={'exam': self.exam.pk, 'pk': self.pk})

class Alternative(models.Model):
    question = models.ForeignKey(Question, verbose_name="Questão")
    text = models.CharField(max_length=100, verbose_name="Texto")

    def __unicode__(self):
        return self.text

    class Meta:
        verbose_name = "Alternativa"
        verbose_name_plural = "Alternativas"

    def get_absolute_url(self):
        return reverse('question_detail', kwargs={'exam': self.question.exam.pk, 'pk': self.question.pk})

    def delete(self):
        if self.question.right_alternative == self:
            self.question.right_alternative = None
            self.question.save()
        super(Alternative, self).delete()

class Answer(models.Model):
    exam = models.ForeignKey(Exam, verbose_name="Prova")
    name = models.CharField(max_length=100, verbose_name="Nome do Aluno")
    grade = models.DecimalField(max_digits=5, decimal_places=2, verbose_name="Nota", blank=True, null=True, default=None)
    answers = models.ManyToManyField(Question, through="Log", verbose_name="Respostas")
    date = models.DateTimeField(auto_now_add=True, verbose_name="Data Recebida")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "Resposta"
        verbose_name_plural = "Resposta"

class Log(models.Model):
    answer = models.ForeignKey(Answer, verbose_name="Resposta")
    question = models.ForeignKey(Question, verbose_name="Pergunta")
    alternative = models.ForeignKey(Alternative, blank=True, null=True, verbose_name="Alternativa")

    def __unicode__(self):
        return self.answer.name

    class Meta:
        verbose_name = "Uma Resposta"
        verbose_name_plural = "Uma Resposta"

apps/administrator/exams/forms.py
# -*- coding: utf-8 -*-
# Python
# Django
from django import forms
# Project
from .models import Exam, Question, Alternative

class ExamForm(forms.ModelForm):
    date = forms.DateField()
    class Meta:
        model = Exam
        fields = (
            "user",
            "name",
            "date"
        )

class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = (
            "exam",
            "text",
        )

class AlternativeForm(forms.ModelForm):
    right = forms.BooleanField(required=False)

    class Meta:
        model = Alternative
        fields = (
            "question",
            "text",
        )

    def save(self, commit=True):
        alternative = super(AlternativeForm, self).save()
        if self.cleaned_data['right']:
            alternative.question.right_alternative = alternative
            alternative.question.save()
        return alternative

apps/administrator/exams/views.py
# -*- coding: utf-8 -*-
# Python
# Django
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.core.urlresolvers import reverse, reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
# Project
from apps.api.useful import make_response
# Models
from django.contrib.auth.models import User
from .models import Exam, Question, Alternative, Answer, Log
# Forms
from .forms import ExamForm, QuestionForm, AlternativeForm
# Mixins
from apps.administrator.main.mixins import LoginRequiredMixin

# Create your views here.
class UsersExamMixin(object):
    def dispatch(self, *args, **kwargs):
        exam = get_object_or_404(Exam, pk=kwargs['exam'])
        if exam.user != self.request.user:
            return redirect('login')
        return super(UsersExamMixin, self).dispatch(*args, **kwargs)

class ExamToContextMixin(object):
    def get_context_data(self, **kwargs):
        context = super(ExamToContextMixin, self).get_context_data(**kwargs)
        context['exam'] = get_object_or_404(Exam, pk=self.kwargs['exam'])
        return context

class ExamNotActiveOrClosedMixin(object):
    def dispatch(self, *args, **kwargs):
        exam = get_object_or_404(Exam, pk=kwargs['exam'])
        if exam.active or exam.closed:
            messages.add_message(self.request, messages.ERROR, 'exam_active_or_closed')
            return redirect('exam_detail', exam = exam.pk)
        return super(ExamNotActiveOrClosedMixin, self).dispatch(*args, **kwargs)

class DeleteSucessMessageMixing(object):
    def delete(self, request, *args, **kwargs):
        messages.add_message(request, messages.SUCCESS, self.success_message)
        return super(DeleteSucessMessageMixing, self).delete(request, *args, **kwargs)

# Lists all exams orderd by date and paginated
class ExamList(LoginRequiredMixin, ListView):
    template_name = 'exam/exam_list.html'
    queryset = Exam.objects.all().order_by('date')
    paginate_by = 10

    def get_queryset(self):
        return self.queryset.filter(user = self.request.user)

# Shows Exam details
class ExamDetail(LoginRequiredMixin, UsersExamMixin, DetailView):
    template_name = 'exam/exam_detail.html'
    model = Exam

    def get_object(self):
        exam = get_object_or_404(Exam, pk=self.kwargs['exam'])
        return exam

    def get_context_data(self, **kwargs):
        context = super(ExamDetail, self).get_context_data(**kwargs)
        context['questions'] = self.object.question_set.all().order_by('id')
        return context

# Controls behavior to create a new Exam
class ExamCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    template_name = 'exam/exam_form.html'
    model = Exam
    form_class = ExamForm
    success_message = 'create_success'

# Controls behavior to update a Exam
class ExamUpdate(SuccessMessageMixin, ExamNotActiveOrClosedMixin, LoginRequiredMixin, UsersExamMixin, UpdateView):
    template_name = 'exam/exam_form.html'
    model = Exam
    form_class = ExamForm
    success_message = 'update_success'

    def get_object(self):
        exam = get_object_or_404(Exam, pk=self.kwargs['exam'])
        return exam

# View that controls the delete of a Question
class ExamDelete(DeleteSucessMessageMixing, ExamNotActiveOrClosedMixin, LoginRequiredMixin, DeleteView):
    model = Exam
    template_name = 'exam/exam_delete.html'
    success_url = reverse_lazy('exam_list')
    success_message = 'exam_delete_success'

    def get_object(self):
        exam = get_object_or_404(Exam, pk=self.kwargs['exam'])
        return exam

# Shows Question details
class QuestionDetail(LoginRequiredMixin, UsersExamMixin, ExamToContextMixin, DetailView):
    template_name = 'question/question_detail.html'
    model = Question

    def get_context_data(self, **kwargs):
        context = super(QuestionDetail, self).get_context_data(**kwargs)
        context['alternatives'] = self.object.alternative_set.all().order_by('id')
        return context

# Controls behavior to create a new Question
class QuestionCreate(SuccessMessageMixin, UsersExamMixin, LoginRequiredMixin, ExamToContextMixin, CreateView):
    template_name = 'question/question_form.html'
    model = Question
    form_class = QuestionForm
    success_message = 'question_create_success'

# Controls behavior to update a Exam
class QuestionUpdate(SuccessMessageMixin, ExamNotActiveOrClosedMixin, UsersExamMixin, LoginRequiredMixin, ExamToContextMixin, UpdateView):
    template_name = 'question/question_form.html'
    model = Question
    form_class = QuestionForm
    success_message = 'question_update_success'

# View that controls the delete of a Question
class QuestionDelete(DeleteSucessMessageMixing, ExamNotActiveOrClosedMixin, LoginRequiredMixin, DeleteView):
    model = Question
    template_name = 'question/question_delete.html'
    success_url = ''
    success_message = 'question_delete_success'

    def get_success_url(self):
        return reverse('exam_detail', kwargs={'exam': self.object.exam.pk })

class QuestionToContextMixin(object):
    def get_context_data(self, **kwargs):
        context = super(QuestionToContextMixin, self).get_context_data(**kwargs)
        context['question'] = get_object_or_404(Question, pk=self.kwargs['question'])
        return context

# Controls behavior to create a new Question
class AlternativeCreate(SuccessMessageMixin, UsersExamMixin, LoginRequiredMixin, ExamToContextMixin, QuestionToContextMixin, CreateView):
    template_name = 'alternative/alternative_form.html'
    model = Alternative
    form_class = AlternativeForm
    success_message = 'alternative_create_success'

# Controls behavior to update a Exam
class AlternativeUpdate(SuccessMessageMixin, ExamNotActiveOrClosedMixin, UsersExamMixin, LoginRequiredMixin, ExamToContextMixin, QuestionToContextMixin, UpdateView):
    template_name = 'alternative/alternative_form.html'
    model = Alternative
    form_class = AlternativeForm
    success_message = 'alternative_update_success'

# View that controls the delete of a Alternative
class AlternativeDelete(DeleteSucessMessageMixing, ExamNotActiveOrClosedMixin, LoginRequiredMixin, DeleteView):
    model = Alternative
    template_name = 'alternative/alternative_delete.html'
    success_url = ''
    success_message = 'alternative_delete_success'

    def get_success_url(self):
        return reverse('question_detail', kwargs={'exam': self.object.question.exam.pk, 'pk': self.object.question.pk})

# View that activates a test to be synchronized
class ExamActivateView(UsersExamMixin, LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        exam = get_object_or_404(Exam.objects.filter(active=False, closed=False), pk=kwargs['exam'])
        Exam.objects.filter(active=True, closed=False).update(active=False, closed=True)
        for question in exam.question_set.all():
            if question.right_alternative == None:
                messages.add_message(request, messages.ERROR, 'answers_not_in')
                return redirect('exam_detail', exam = exam.pk)
        exam.active = True
        exam.save()
        messages.add_message(request, messages.SUCCESS, 'exam_activated')
        return redirect('exam_report', exam = exam.pk)

# View that closes a test to be synchronized
class ExamCloseView(UsersExamMixin, LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        exam = get_object_or_404(Exam.objects.filter(active=True, closed=False), pk=kwargs['exam'])
        exam.active = False
        exam.closed = True
        exam.save()
        messages.add_message(request, messages.SUCCESS, 'exam_closed')
        return redirect('exam_detail', exam = exam.pk)

# Shows Exam Report
class ExamReport(LoginRequiredMixin, UsersExamMixin, DetailView):
    template_name = 'exam/exam_report.html'
    model = Exam

    def get_object(self):
        exam = get_object_or_404(Exam, pk=self.kwargs['exam'])
        return exam

# Shows Exam Report
class ExamReportData(LoginRequiredMixin, UsersExamMixin, DetailView):
    template_name = ""
    model = Exam

    def get_object(self):
        exam = get_object_or_404(Exam, pk=self.kwargs['exam'])
        return exam

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        answers = self.object.answer_set.all().order_by('id')
        response = serialize_answers(answers)
        return make_response(response)

def serialize_answers(answers):
    new_answers = []
    for a in answers:
        new_answer = {
            "name": a.name,
            "grade": None if a.grade == None else float(a.grade),
            "date": str(a.date),
            "logs": []
        }
        for l in Log.objects.filter(answer = a).order_by("question__id"):
            new_log = {
                "question_id": l.question.id,
                "question": l.question.text,
                "alternative_id": None if l.alternative == None else l.alternative.id,
                "alternative": "-" if l.alternative == None else l.alternative.text
            }
            new_answer['logs'].append(new_log)

        new_answers.append(new_answer)
    return new_answers

apps/administrator/exams/templates/exam/exam_delete.html
{% extends "base/admin_delete_base.html" %}
{% block title %} Prova > {{ exam.name }} > {% endblock %}
{% block back_button_url %}{% url 'exam_detail' exam.id %}{% endblock %}

apps/administrator/exams/templates/exam/exam_detail.html
{% extends "base/admin_detail_base.html" %}
{% block title %} Prova > {{ exam.name }} {% endblock %}
{% block update_button_url %}{% url 'exam_update' exam.pk %}{% endblock %}
{% block delete_button_url %}{% url 'exam_delete' exam.pk %}{% endblock %}
{% block back_button_url %}{% url 'exam_list' %}{% endblock %}
{% block details %}
{% csrf_token %}

{# Only show options that the user can do! #}
{% if not exam.active and not exam.closed %}
  <a href="{% url 'question_add' exam.pk %}">Nova Questão</a>
{% endif %}

<h1>{{ exam.name }}</h1>

{% if exam.active and not exam.closed %}
  Prova Ativa! <a href="{% url 'exam_report' exam.pk %}">Acompanhe as Notas!</a>
{% elif not exam.active and exam.closed %}
  Prova Fechada! <a href="{% url 'exam_report' exam.pk %}">Veja as Notas!</a>
{% else %}
  Em Construção!
  <a onclick="confirmActivation()">Ativar</a>
{% endif %}

<h1>Perguntas</h1>
{% for question in questions %}
<a href="{% url 'question_detail' exam.pk question.pk %}">{{ question.text }}</a>
{% if question.right_alternative != None %}Pronta!{% endif %}
<br>
{% endfor %}

<script>
function confirmActivation() {
  if (confirm("Tem certeza que deseja activa esse prova?\nVocê não poderá mais editá-la")) {
    location.href = "{% url 'exam_activate' exam.pk %}"
  }
}

{% for message in messages %}
  {% if message.message == "answers_not_in" %}
    alert("Todas as perguntas devem ter uma alternativa certa");
  {% elif message.message == "exam_closed" %}
    alert("Prova fechada com sucesso!");
  {% elif message.message == "exam_active_or_closed" %}
    alert("Provas ativas ou fechados não podems ser atualizados ou excluidos");
  {% elif message.message == "question_delete_success" %}
    alert("Questão deletada com sucesso!");
  {% elif message.message == "create_success" %}
    alert("Prova Criada com sucesso!");
  {% elif message.message == "update_success" %}
    alert("Prova Atualizada com sucesso!");
  {% endif %}
{% endfor %}
</script>
{% endblock %}

apps/administrator/exams/templates/exam/exam_form.html
{% extends "base/admin_form_base.html" %}
{% block title %} Prova > {% if object %}{{ exam.name }}{% else %}Novo{% endif %} {% endblock %}
{% block back_button_url %}{% if object %}{% url 'exam_detail' object.id %}{% else %}{% url 'exam_list' %}{% endif %}{% endblock %}
{% block form %}
  <input type="hidden" name="user" value="{{ user.pk }}">
  <label for="id_name">
    Nome: {{ form.name }}
  </label>
  <label for="id_date">
    Data: <input type="date" name="date" id="id_date" value="{{ form.date.value|date:"Y-m-d" }}">
  </label>
  <input type="submit" name="go" value="{% if object %} Atualizar {% else %} Adicionar {% endif %}">
{% endblock %}

apps/administrator/exams/templates/exam/exam_list.html
{% extends "base/admin_list_base.html" %}
{% block title %} Provas {% endblock %}
{% block add_button_url %}{% url 'exam_add' %}{% endblock %}
{% block list %}
  {% for obj in object_list %}
  <a href="{% url 'exam_detail' obj.pk %}">{{ obj.name }}</a><br>
  {% endfor %}
{% endblock %}
{% block extra_content %}
<script>
{% for message in messages %}
  {% if message.message == "exam_delete_success" %}
    alert("Prova deletada com sucesso!");
  {% endif %}
{% endfor %}
</script>
{% endblock %}
{% block pagination_url %}{% url 'exam_list_admin_pag' n %}{% endblock %}

apps/administrator/exams/templates/exam/exam_report.html
{% extends "base/admin_detail_base.html" %}
{% block title %} Prova > {{ exam.name }} {% endblock %}
{% block update_button %}{% endblock %}
{% block back_button_url %}{% url 'exam_detail' exam.pk %}{% endblock %}
{% block delete_button %}{% endblock %}
{% block details %}
{% csrf_token %}
{% if exam.active and not exam.closed %}
<a onclick="confirmClosing()">Fechar</a>
{% endif %}

<h1>{{ exam.name }}</h1>

<div id="answers-container"></div>

{% verbatim %}
<script id="answers-template" type="text/template">
  {{#each answers}}
  {{ name }} - {{ grade }} - {{ date date }}<br>
  {{/each}}
</script>
{% endverbatim %}

<script>

answers_template = Handlebars.compile($("#answers-template").html());
function loadAnswers() {
  setupAjax();
  $.ajax({
    type: "POST",
    url: "{% url 'exam_report_data' exam.id %}",
    // Sending new causes the view to send geo data
    data: {},
    datatype: "json",
    success: function (response) {
      response = JSON.parse(response)
      console.log("RELOADED");
      $("#answers-container").html(answers_template({"answers": response}))
    },
    error: error
  });
}
loadAnswers();
{% if exam.active and not exam.closed %}
function confirmClosing() {
  if (confirm("Tem certeza que deseja fechar esse prova?")) {
    location.href = "{% url 'exam_close' exam.pk %}"
  }
}
setInterval(loadAnswers, 10000)
{% endif %}

{% for message in messages %}
  {% if message.message == "exam_activated" %}
    alert("Prova ativada com sucesso!");
  {% endif %}
{% endfor %}
</script>
{% endblock %}